language: java
sudo: false # faster builds
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk11
  - oraclejdk14
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean test jacoco:report coveralls:report