language: java
sudo: false # faster builds
dist: trusty
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token